name = "Connoisseur"
license = "MIT"
licenselink = "https://github.com/josephrexme/connoiseur/blob/master/LICENSE.md"
description = "A minimalist blog theme with portfolio"
homepage = "https://github.com/josephrexme/connoiseur"
tags = ["blog", "animation", "minimalist"]
features = ["syntax highlighting", "blog", "pagination", "sharing options", "Reading Time", "Read progress", "custom 404"]
min_version = 0.20

[author]
  name = "Joseph Rex"
  homepage = "https://josephrex.me"
